// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: MaxWeightGoal.sql

package db

import (
	"context"
)

const createMaxWeightGoal = `-- name: CreateMaxWeightGoal :one
INSERT INTO MaxWeightGoal (username, exercise_id, goal_weight, notes)
VALUES ($1, $2, $3, $4)
RETURNING goal_id, username, exercise_id, goal_weight, notes, created_at
`

type CreateMaxWeightGoalParams struct {
	Username   string `json:"username"`
	ExerciseID int64  `json:"exercise_id"`
	GoalWeight int32  `json:"goal_weight"`
	Notes      string `json:"notes"`
}

func (q *Queries) CreateMaxWeightGoal(ctx context.Context, arg CreateMaxWeightGoalParams) (Maxweightgoal, error) {
	row := q.db.QueryRow(ctx, createMaxWeightGoal,
		arg.Username,
		arg.ExerciseID,
		arg.GoalWeight,
		arg.Notes,
	)
	var i Maxweightgoal
	err := row.Scan(
		&i.GoalID,
		&i.Username,
		&i.ExerciseID,
		&i.GoalWeight,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaxWeightGoal = `-- name: DeleteMaxWeightGoal :exec
DELETE FROM MaxWeightGoal
WHERE goal_id = $1
`

func (q *Queries) DeleteMaxWeightGoal(ctx context.Context, goalID int64) error {
	_, err := q.db.Exec(ctx, deleteMaxWeightGoal, goalID)
	return err
}

const getMaxWeightGoal = `-- name: GetMaxWeightGoal :one
SELECT goal_id, username, exercise_id, goal_weight, notes, created_at
FROM MaxWeightGoal
WHERE goal_id = $1
`

func (q *Queries) GetMaxWeightGoal(ctx context.Context, goalID int64) (Maxweightgoal, error) {
	row := q.db.QueryRow(ctx, getMaxWeightGoal, goalID)
	var i Maxweightgoal
	err := row.Scan(
		&i.GoalID,
		&i.Username,
		&i.ExerciseID,
		&i.GoalWeight,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listMaxWeightGoals = `-- name: ListMaxWeightGoals :many
SELECT goal_id, username, exercise_id, goal_weight, notes, created_at
FROM MaxWeightGoal
WHERE username = $1 AND exercise_id = $2
ORDER BY goal_id -- You can change the ORDER BY clause to order by a different column if needed
LIMIT $3
OFFSET $4
`

type ListMaxWeightGoalsParams struct {
	Username   string `json:"username"`
	ExerciseID int64  `json:"exercise_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListMaxWeightGoals(ctx context.Context, arg ListMaxWeightGoalsParams) ([]Maxweightgoal, error) {
	rows, err := q.db.Query(ctx, listMaxWeightGoals,
		arg.Username,
		arg.ExerciseID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Maxweightgoal{}
	for rows.Next() {
		var i Maxweightgoal
		if err := rows.Scan(
			&i.GoalID,
			&i.Username,
			&i.ExerciseID,
			&i.GoalWeight,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaxWeightGoal = `-- name: UpdateMaxWeightGoal :one
UPDATE MaxWeightGoal
SET exercise_id = $2, goal_weight = $3, notes = $4
WHERE goal_id = $1
RETURNING goal_id, username, exercise_id, goal_weight, notes, created_at
`

type UpdateMaxWeightGoalParams struct {
	GoalID     int64  `json:"goal_id"`
	ExerciseID int64  `json:"exercise_id"`
	GoalWeight int32  `json:"goal_weight"`
	Notes      string `json:"notes"`
}

func (q *Queries) UpdateMaxWeightGoal(ctx context.Context, arg UpdateMaxWeightGoalParams) (Maxweightgoal, error) {
	row := q.db.QueryRow(ctx, updateMaxWeightGoal,
		arg.GoalID,
		arg.ExerciseID,
		arg.GoalWeight,
		arg.Notes,
	)
	var i Maxweightgoal
	err := row.Scan(
		&i.GoalID,
		&i.Username,
		&i.ExerciseID,
		&i.GoalWeight,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
