// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (int64, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (int64, error)
	CreateMaxRepGoal(ctx context.Context, arg CreateMaxRepGoalParams) (int64, error)
	CreateMaxWeightGoal(ctx context.Context, arg CreateMaxWeightGoalParams) (int64, error)
	CreateMuscleGroup(ctx context.Context, muscleGroupName string) (int64, error)
	CreateRep(ctx context.Context, arg CreateRepParams) (int64, error)
	CreateSet(ctx context.Context, arg CreateSetParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (Userprofile, error)
	CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (int64, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (int64, error)
	CreateWorkoutprogram(ctx context.Context, arg CreateWorkoutprogramParams) (int64, error)
	DeleteEquipment(ctx context.Context, equipmentID int64) error
	DeleteExercise(ctx context.Context, exerciseID int64) error
	DeleteMaxRepGoal(ctx context.Context, goalID int64) error
	DeleteMuscleGroup(ctx context.Context, muscleGroupID int64) error
	DeleteRep(ctx context.Context, repID int64) error
	DeleteSet(ctx context.Context, setID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	DeleteUserProfile(ctx context.Context, userID int64) error
	DeleteWeightEntry(ctx context.Context, weightEntryID int64) error
	DeleteWeightRepGoal(ctx context.Context, goalID int64) error
	DeleteWorkout(ctx context.Context, workoutID int64) error
	DeleteWorkoutprogram(ctx context.Context, programID int64) error
	GetEquipment(ctx context.Context, equipmentID int64) (Equipment, error)
	GetExercise(ctx context.Context, exerciseID int64) (Exercise, error)
	GetMaxRepGoal(ctx context.Context, goalID int64) (Maxrepgoal, error)
	GetMaxWeightGoal(ctx context.Context, goalID int64) (Maxweightgoal, error)
	GetMuscleGroup(ctx context.Context, muscleGroupID int64) (Musclegroup, error)
	GetRep(ctx context.Context, repID int64) (Rep, error)
	GetSet(ctx context.Context, setID int64) (Set, error)
	GetUser(ctx context.Context, userID int64) (GetUserRow, error)
	GetUserProfile(ctx context.Context, userID int64) (GetUserProfileRow, error)
	GetWeightEntry(ctx context.Context, weightEntryID int64) (Weightentry, error)
	GetWorkout(ctx context.Context, workoutID int64) (Workout, error)
	GetWorkoutprogram(ctx context.Context, programID int64) (Workoutprogram, error)
	ListEquipments(ctx context.Context, arg ListEquipmentsParams) ([]ListEquipmentsRow, error)
	ListExercise(ctx context.Context, arg ListExerciseParams) ([]ListExerciseRow, error)
	ListMaxRepGoals(ctx context.Context, arg ListMaxRepGoalsParams) ([]ListMaxRepGoalsRow, error)
	ListMaxWeightGoals(ctx context.Context, arg ListMaxWeightGoalsParams) ([]ListMaxWeightGoalsRow, error)
	ListMuscleGroups(ctx context.Context, arg ListMuscleGroupsParams) ([]Musclegroup, error)
	ListReps(ctx context.Context, arg ListRepsParams) ([]ListRepsRow, error)
	ListSets(ctx context.Context, arg ListSetsParams) ([]ListSetsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWeightEntries(ctx context.Context, arg ListWeightEntriesParams) ([]ListWeightEntriesRow, error)
	ListWorkoutprograms(ctx context.Context, arg ListWorkoutprogramsParams) ([]ListWorkoutprogramsRow, error)
	ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]ListWorkoutsRow, error)
	UpdateEquipment(ctx context.Context, arg UpdateEquipmentParams) (Equipment, error)
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error)
	UpdateMaxRepGoal(ctx context.Context, arg UpdateMaxRepGoalParams) (Maxrepgoal, error)
	UpdateMaxWeightGoal(ctx context.Context, arg UpdateMaxWeightGoalParams) (Maxweightgoal, error)
	UpdateMuscleGroup(ctx context.Context, arg UpdateMuscleGroupParams) (Musclegroup, error)
	UpdateRep(ctx context.Context, arg UpdateRepParams) (Rep, error)
	UpdateSet(ctx context.Context, arg UpdateSetParams) (Set, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (Userprofile, error)
	UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) (Weightentry, error)
	UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error)
	UpdateWorkoutprogram(ctx context.Context, arg UpdateWorkoutprogramParams) (Workoutprogram, error)
}

var _ Querier = (*Queries)(nil)
