// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: Set.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
INSERT INTO Set (workout_id, exercise_id, set_number, weight, rest_duration, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING set_id, workout_id, exercise_id, set_number, weight, rest_duration, notes
`

type CreateSetParams struct {
	WorkoutID    int64           `json:"workout_id"`
	ExerciseID   int64           `json:"exercise_id"`
	SetNumber    int32           `json:"set_number"`
	Weight       pgtype.Float8   `json:"weight"`
	RestDuration pgtype.Interval `json:"rest_duration"`
	Notes        pgtype.Text     `json:"notes"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Weight,
		arg.RestDuration,
		arg.Notes,
	)
	var i Set
	err := row.Scan(
		&i.SetID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Weight,
		&i.RestDuration,
		&i.Notes,
	)
	return i, err
}

const deleteSet = `-- name: DeleteSet :exec
DELETE FROM Set
WHERE set_id = $1
`

func (q *Queries) DeleteSet(ctx context.Context, setID int64) error {
	_, err := q.db.Exec(ctx, deleteSet, setID)
	return err
}

const getSet = `-- name: GetSet :one
SELECT set_id, workout_id, exercise_id, set_number, weight, rest_duration, notes
FROM Set
WHERE set_id = $1
`

func (q *Queries) GetSet(ctx context.Context, setID int64) (Set, error) {
	row := q.db.QueryRow(ctx, getSet, setID)
	var i Set
	err := row.Scan(
		&i.SetID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Weight,
		&i.RestDuration,
		&i.Notes,
	)
	return i, err
}

const listSets = `-- name: ListSets :many
SELECT set_id, workout_id, exercise_id, set_number, weight, rest_duration, notes
FROM Set
ORDER BY set_id -- You can change the ORDER BY clause to order by a different column if needed
LIMIT $1
OFFSET $2
`

type ListSetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSets(ctx context.Context, arg ListSetsParams) ([]Set, error) {
	rows, err := q.db.Query(ctx, listSets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.SetID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Weight,
			&i.RestDuration,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSet = `-- name: UpdateSet :one
UPDATE Set
SET set_number = $2, weight = $3, rest_duration = $4, notes = $5
WHERE set_id = $1
RETURNING set_id, workout_id, exercise_id, set_number, weight, rest_duration, notes
`

type UpdateSetParams struct {
	SetID        int64           `json:"set_id"`
	SetNumber    int32           `json:"set_number"`
	Weight       pgtype.Float8   `json:"weight"`
	RestDuration pgtype.Interval `json:"rest_duration"`
	Notes        pgtype.Text     `json:"notes"`
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, updateSet,
		arg.SetID,
		arg.SetNumber,
		arg.Weight,
		arg.RestDuration,
		arg.Notes,
	)
	var i Set
	err := row.Scan(
		&i.SetID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Weight,
		&i.RestDuration,
		&i.Notes,
	)
	return i, err
}
