Project MyFitnessApp {
  database_type: 'PostgreSQL'
  Note: '''
    # My fitness app database
    **markdown content here**
  '''
}

Enum "EquipmentType" {
  "Barbell"
  "Dumbbell"
  "Machine"
  "Bodyweight"
  "Other"
}

Enum "CompletionEnum" {
  "Completed"
  "Incomplete"
  "NotStarted"
}

Enum "WeightUnit" {
  "kg"
  "lb"
}

Enum "MuscleGroupEnum" {
  "Chest"
  "Back"
  "Legs"
  "Shoulders"
  "Arms"
  "Abs"
  "Cardio"
}

Enum "WorkoutGoalEnum" {
  "Build Muscle"
  "Lose Weight"
  "Improve Endurance"
  "Maintain Fitness"
  "Tone Body"
  "Custom"
}

Enum "Difficulty" {
  "Beginner"
  "Intermediate"
  "Advanced"
}

Enum "Visibility" {
  "Public"
  "Private"
}

Enum "Rating" {
  "1"
  "2"
  "3"
  "4"
  "5"
}

Enum "FatigueLevel" {
  "Very Light"
  "Light"
  "Moderate"
  "Heavy"
  "Very Heavy"
}

Table "User" {
  "username" VARCHAR(255) [pk, not null]
  "email" VARCHAR(255) [unique, not null]
  "password_hash" VARCHAR(255) [not null]
  "password_changed_at" timestamptz [not null, default: "0001-01-01 00:00:00z"]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "UserProfile" {
  "user_profile_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [unique, not null]
  "full_name" VARCHAR(255) [not null]
  "age" INT [not null]
  "gender" VARCHAR(10) [not null]
  "height_cm" INT [not null]
  "height_ft_in" VARCHAR(20) [not null]
  "preferred_unit" WeightUnit [not null]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "AvailableWorkoutPlans" {
  "plan_id" BIGSERIAL [pk, increment]
  "plan_name" VARCHAR(255) [not null]
  "description" VARCHAR(255) [not null, default: `''`]
  "goal" WorkoutGoalEnum [not null, default: `'Lose Weight'`]
  "difficulty" Difficulty [not null, default: `'Light'`]
  "is_public" Visibility [not null, default: `'Private'`]
  "created_at" timestamptz [not null, default: `now()`]
  "updated_at" timestamptz [not null, default: `now()`]
  "creator_username" VARCHAR(255) [not null]
}

Table "WorkoutPlan" {
  "plan_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [unique, not null]
  "plan_name" VARCHAR(255) [unique, not null]
  "description" TEXT [not null, default: `''`]
  "start_date" timestamptz [not null, default: `now()`]
  "end_date" timestamptz [not null, default: `now()`]
  "goal" WorkoutGoalEnum [not null, default: `'Lose Weight'`]
  "difficulty" Difficulty [not null, default: `'Beginner'`]
  "is_public" Visibility [not null, default: `'Public'`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "Workout" {
  "workout_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [not null]
  "workout_date" timestamptz [not null, default: `now()`]
  "workout_duration" VARCHAR(8) [not null, default: `''`]
  "fatigue_level" FatigueLevel [not null, default: `'Very Light'`]
  "notes" VARCHAR(255) [not null, default: `''`]
  "total_calories_burned" INT [not null, default: `0`]
  "total_distance" INT [not null, default: `0`]
  "total_repetitions" INT [not null, default: `0`]
  "total_sets" INT [not null, default: `0`]
  "total_weight_lifted" INT [not null, default: `0`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "Exercise" {
  "exercise_name" VARCHAR(255) [unique, pk, not null]
  "equipment_required" EquipmentType [unique, not null, default: `'Barbell'`]
  "description" VARCHAR(255) [not null, default: `''`]
  "muscle_group_name" MuscleGroupEnum [not null]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "AvailablePlanExercises" {
  "id" BIGSERIAL [pk, increment]
  "plan_id" BIGINT [not null]
  "exercise_name" VARCHAR(255) [not null]
  "sets" INT [not null, default: `0`]
  "rest_duration" VARCHAR [not null, default: `''`]
  "notes" VARCHAR [not null, default: `''`]
}

Table "OneOffWorkoutExercise" {
  "id" SERIAL [pk, increment]
  "workout_id" BIGINT [unique, not null]
  "exercise_name" VARCHAR(255) [unique, not null]
  "description" VARCHAR(255) [not null, default: `''`]
  "muscle_group_name" MuscleGroupEnum [not null]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "WorkoutLog" {
  "log_id" BIGSERIAL [pk, increment]
  "username" VARCHAR [not null]
  "plan_id" BIGINT [not null]
  "log_date" timestamptz [not null, default: `now()`]
  "rating" Rating [not null, default: `'1'`]
  "fatigue_level" FatigueLevel [not null, default: `'Very Light'`]
  "overall_feeling" TEXT [not null, default: `''`]
  "comments" TEXT [not null, default: `''`]
  "workout_duration" VARCHAR(10) [not null, default: `'0m'`]
  "total_calories_burned" INT [not null, default: `0`]
  "total_distance" INT [not null, default: `0`]
  "total_repetitions" INT [not null, default: `0`]
  "total_sets" INT [not null, default: `0`]
  "total_weight_lifted" INT [not null, default: `0`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "ExerciseLog" {
  "exercise_log_id" BIGSERIAL [pk, increment]
  "log_id" BIGINT [not null]
  "exercise_name" VARCHAR(255) [not null]
  "sets_completed" INT [not null, default: `0`]
  "repetitions_completed" INT [not null, default: `0`]
  "weight_lifted" INT [not null, default: `0`]
  "notes" VARCHAR(255) [not null, default: `''`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "ExerciseSet" {
  "set_id" BIGSERIAL [pk, increment]
  "exercise_log_id" BIGINT [not null]
  "set_number" INT [not null]
  "weight_lifted" INT [not null, default: `0`]
  "repetitions_completed" INT [not null, default: `0`]
}

Table "Set" {
  "set_id" BIGSERIAL [pk, increment]
  "exercise_name" VARCHAR(255) [not null]
  "set_number" INT [not null, default: `1`]
  "weight" int [not null, default: `1`]
  "rest_duration" VARCHAR(8) [not null, default: `''`]
  "reps_completed" INT [not null]
  "notes" VARCHAR(255) [not null, default: `''`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "WeightEntry" {
  "weight_entry_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [not null]
  "entry_date" timestamptz [not null, default: `now()`]
  "weight_kg" INT [not null, default: `0`]
  "weight_lb" INT [not null, default: `0`]
  "notes" VARCHAR(255) [not null, default: `''`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "MaxRepGoal" {
  "goal_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [not null]
  "exercise_name" VARCHAR(255) [unique, not null]
  "goal_reps" INT [not null]
  "notes" VARCHAR(255) [not null, default: `''`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "MaxWeightGoal" {
  "goal_id" BIGSERIAL [pk, increment]
  "username" VARCHAR(255) [not null]
  "exercise_name" VARCHAR(255) [unique, not null]
  "goal_weight" INT [not null]
  "notes" VARCHAR(255) [not null, default: `''`]
  "created_at" timestamptz [not null, default: `now()`]
}

Table "sessions" {
  "id" uuid [pk]
  "username" varchar [not null]
  "refresh_token" varchar [not null]
  "user_agent" varchar [not null]
  "client_ip" varchar [not null]
  "is_blocked" boolean [not null, default: false]
  "expires_at" timestamptz [not null]
  "created_at" timestamptz [not null, default: `now()`]
}

Ref:"User"."username" < "UserProfile"."username"

Ref:"User"."username" < "AvailableWorkoutPlans"."creator_username"

Ref:"User"."username" < "WorkoutPlan"."username"

Ref:"User"."username" < "Workout"."username"

Ref:"AvailableWorkoutPlans"."plan_id" < "AvailablePlanExercises"."plan_id"

Ref:"Exercise"."exercise_name" < "AvailablePlanExercises"."exercise_name"

Ref:"Workout"."workout_id" < "OneOffWorkoutExercise"."workout_id"

Ref:"Exercise"."exercise_name" < "OneOffWorkoutExercise"."exercise_name"

Ref:"User"."username" < "WorkoutLog"."username"

Ref:"WorkoutPlan"."plan_id" < "WorkoutLog"."plan_id"

Ref:"WorkoutLog"."log_id" < "ExerciseLog"."log_id"

Ref:"Exercise"."exercise_name" < "ExerciseLog"."exercise_name"

Ref:"ExerciseLog"."exercise_log_id" < "ExerciseSet"."exercise_log_id"

Ref:"Exercise"."exercise_name" < "Set"."exercise_name"

Ref:"User"."username" < "WeightEntry"."username"

Ref:"User"."username" < "MaxRepGoal"."username"

Ref:"Exercise"."exercise_name" < "MaxRepGoal"."exercise_name"

Ref:"User"."username" < "MaxWeightGoal"."username"

Ref:"Exercise"."exercise_name" < "MaxWeightGoal"."exercise_name"

Ref:"User"."username" < "sessions"."username"

